### ISSUE TITLE
Certain stocks do not work for returning price

### ISSUE THREAD

**Issue by TrooperZ** [kj7rrv/stockquotes#1]
I use this code to generate the current price of a stock. 
```			
stSTONK = stockquotes.Stock(stock.upper())
stSTONKprice = stSTONK.current_price
```

However, for certain stocks, like NKLA, it returns `ValueError: could not convert string to float: 'As of  2:06PM EST. Market open.'`.
It works with most of the other stocks.

**Comment by kj7rrv** [comment]
I'm working on fixing it.

FYI, you don't need `.upper()`; it works with lowercase or mixed-case symbols too.

**Comment by kj7rrv** [comment]
I have an experimental fix on my laptop. I'll test it after the market opens Monday and push it if it works.

**Comment by kj7rrv** [comment]
Okay, 2.0.1 should work for NKLA.
