### ISSUE TITLE
ValueError: could not convert string to float

### ISSUE THREAD

**Issue by chrotek** [kj7rrv/stockquotes#3]
I've been using the stockquotes module for quite some time, but it's recently started giving this error!

    / # python3
    Python 3.9.5 (default, May  4 2021, 18:33:52)
    [GCC 10.2.1 20201203] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import stockquotes
    >>> aapl=stockquotes.Stock('AAPL')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python3.9/site-packages/stockquotes/__init__.py", line 97, in __init__
        self.increase_dollars = float(
    ValueError: could not convert string to float: '(-1.17%)'
    >>>

**Comment by kj7rrv** [comment]
I'm looking into it the issue. It looks like Yahoo! changed the HTML structure of Yahoo! Finance, which this module scrapes for data. Unfortunately this might take a while to fix, because I'll have to rewrite quite a bit of the code.

**Comment by kj7rrv** [comment]
Fixed in 43a0a94

This ended up not being as complicated as I expected. Please let me know if you still have problems.
